-- 上海如静知华信息科技有限公司 https://www.zhuatech.cn/
-- 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
CREATE DATABASE IF NOT EXISTS zhuatech_vending DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE zhuatech_vending;

CREATE TABLE product (id VARCHAR(32) PRIMARY KEY, sku VARCHAR(64) NOT NULL UNIQUE, barcode VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, category VARCHAR(64), price DECIMAL(12,2) NOT NULL, cost DECIMAL(12,2) NOT NULL, shelf_life_days INT NOT NULL, status VARCHAR(24) NOT NULL, created_at DATETIME(3) NOT NULL);
CREATE TABLE vending_machine (id VARCHAR(32) PRIMARY KEY, code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(128) NOT NULL, site VARCHAR(255) NOT NULL, model VARCHAR(64), payment_channels JSON NOT NULL, status VARCHAR(24) NOT NULL, token_hash VARCHAR(128), firmware_version VARCHAR(32), temperature DECIMAL(8,2), signal_value INT, last_heartbeat_at DATETIME(3), created_at DATETIME(3) NOT NULL);
CREATE TABLE vending_slot (id VARCHAR(32) PRIMARY KEY, machine_id VARCHAR(32) NOT NULL, slot_code VARCHAR(32) NOT NULL, product_id VARCHAR(32) NOT NULL, capacity INT NOT NULL, quantity INT NOT NULL, reserved INT NOT NULL, safety_stock INT NOT NULL, price DECIMAL(12,2) NOT NULL, status VARCHAR(24) NOT NULL, version BIGINT NOT NULL DEFAULT 0, updated_at DATETIME(3) NOT NULL, UNIQUE KEY uk_machine_slot(machine_id,slot_code));
CREATE TABLE promotion (id VARCHAR(32) PRIMARY KEY, name VARCHAR(128) NOT NULL, promotion_type VARCHAR(24) NOT NULL, promotion_value DECIMAL(12,4) NOT NULL, product_ids JSON NOT NULL, start_at DATETIME(3) NOT NULL, end_at DATETIME(3) NOT NULL, status VARCHAR(24) NOT NULL, created_at DATETIME(3) NOT NULL);
CREATE TABLE vending_order (id VARCHAR(32) PRIMARY KEY, order_no VARCHAR(64) NOT NULL UNIQUE, machine_id VARCHAR(32) NOT NULL, total_amount DECIMAL(12,2) NOT NULL, discount_amount DECIMAL(12,2) NOT NULL, payable_amount DECIMAL(12,2) NOT NULL, refund_amount DECIMAL(12,2), status VARCHAR(24) NOT NULL, channel VARCHAR(24), trade_no VARCHAR(128), refund_trade_no VARCHAR(128), expires_at DATETIME(3) NOT NULL, paid_at DATETIME(3), completed_at DATETIME(3), refunded_at DATETIME(3), created_at DATETIME(3) NOT NULL);
CREATE TABLE vending_order_line (id BIGINT PRIMARY KEY AUTO_INCREMENT, order_id VARCHAR(32) NOT NULL, slot_id VARCHAR(32) NOT NULL, product_id VARCHAR(32) NOT NULL, quantity INT NOT NULL, unit_price DECIMAL(12,2) NOT NULL, amount DECIMAL(12,2) NOT NULL, discount DECIMAL(12,2) NOT NULL, dispense_status VARCHAR(24));
CREATE TABLE replenishment (id VARCHAR(32) PRIMARY KEY, machine_id VARCHAR(32) NOT NULL, lines JSON NOT NULL, status VARCHAR(24) NOT NULL, assignee VARCHAR(64), created_at DATETIME(3) NOT NULL, completed_at DATETIME(3));
CREATE TABLE vending_work_order (id VARCHAR(32) PRIMARY KEY, machine_id VARCHAR(32) NOT NULL, fault_code VARCHAR(64) NOT NULL, description VARCHAR(512) NOT NULL, severity VARCHAR(16) NOT NULL, status VARCHAR(24) NOT NULL, assignee VARCHAR(64), resolution VARCHAR(512), created_at DATETIME(3) NOT NULL, closed_at DATETIME(3));
CREATE TABLE audit_event (id VARCHAR(32) PRIMARY KEY, actor VARCHAR(64) NOT NULL, action VARCHAR(64) NOT NULL, resource_id VARCHAR(64) NOT NULL, detail JSON, occurred_at DATETIME(3) NOT NULL);
